[project]
name = 'decentralized-skill-certification-network'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.credential-verification-system]
path = 'contracts/credential-verification-system.clar'
clarity_version = 3
epoch = 3.1

[contracts.skill-assessment-coordinator]
path = 'contracts/skill-assessment-coordinator.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
